# Generated by Django 3.1.7 on 2021-04-14 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_sqr_mtrs', models.BooleanField(default=False)),
                ('is_quantified', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='ironwork_comments',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='ironwork_price',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.CreateModel(
            name='ComplementMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('quantity', models.IntegerField()),
                ('complement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coti.complement')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coti.material')),
            ],
        ),
    ]
